### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by fuzebox1** [johannesthyssen/vim-signit#3]
I like this project, but i find myself using it together with another, vim-header in order to add all the info i want.
A problem for me with both is that if the file is say a .py, it doesn't add #!/usr/bin/env python at the very top.

Id like to see this awesome little vim plugin include a function to add custom file header information as well.

Id like :Signit to be able to add something like:

```
#!/usr/bin/env python (customizable trough vimrc g:env?)
# -*- coding: utf-8 -*-  <- If vimrc has set encoding=utf-8
# ASCII Goes here
# to the right of ASCII goes @name, @link1-2, @email (read from .git repo perhaps, or add own in vimrc)
# @Last modified time, auto updates perhaps
# @Editor used and vim-settings, like spacing, tabstops etc
# @Custom information string
```

Maybe it could even skip the ASCII if figlet/toilet is not installed? Or as an option.

I realize this might be more work than you want to put in to it. I would if i had the time to learn more about vimscripting... I would appreciate it a lot though.

**Comment by johannesthyssen** [comment]
Hi @fuzebox1! I am glad you like this project. Since the focus of Signit is mainly dotfile aesthetics I would like to keep it simple and as it is. I have limited it to only two extra lines of information to keep the lines of text within the height of the ASCII Art. I could definetely make the ASCII art optional, however that is the whole point of the plugin. Sorry ):
